exp:
  expname: chest_50
  datadir: ./data/ct_data/chest_50.pickle
  device: cuda # cuda or mps or cpu
network:
  net_type: MLP # MLP or RAD-UNet
encoder:
  encoding: PSNR # PSNR or HASH
train:
  epoch: 1010
  n_points: 192
  n_rays: 2048
log:
  i_eval: 10  # Epoch for evaluation
  i_save: 1000  # Epoch for saving