exp:
  expname: jaw_50
  datadir: ./data/ct_data/jaw_50.pickle
  device: cuda # cuda or mps or cpu
network:
  net_type: RAD-UNet # MLP or RAD-UNet
encoder:
  encoding: HASH # PSNR or HASH
train:
  epoch: 1010
  n_points: 192
  n_rays: 2048
log:
  i_eval: 10  # Epoch for evaluation
  i_save: 100  # Epoch for saving